### ISSUE TITLE
Pump for water transfer 

### ISSUE THREAD

**Issue by DTGteam1** [Teemill/POD_factory#5]
with the pre-treat it is quite difficult to lift the 20 litter water container to fill up the pre-treat water tank so we would like a pump or system to help transfer water from the 20 littler container to the pre-treat water tank.

**Comment by martdog** [comment]
Pickup pipe from floor - order some pipe (2m)

**Comment by DTGteam1** [comment]
i will order this today

**Comment by martdog** [comment]
Ask amaya for it

**Comment by DTGteam1** [comment]
OK yer i will ask and see what they say
